---
title: "Размеченный текст"
---
<text>
<p>... Так кто ж ты, наконеи?</p>
<p>— Я - часть той силы,</p>
<p>чио вечно хочет</p>
<p>зла и вечно совершает благо.</p>
<p>Гете, «Фауст»</p>
<p>ГЛАВА 1</p>
<p>Никогда не разговаривайте с неизвестными</p>
<p>Однажды весною, в час небывало жаркого заката, в <place type='city'>Москва</place>,</p>
<p>на <place type='park'>Патриаршие пруды</place>, появились два гражданина. Первый</p>
<p>из них, одетый в летнюю серенькую пару, был маленького роста, упитан, лыс, свою приличную шляпу пирожком нес в руке,</p>
<p>а на хорошо выбритом лице его помещались сверхъестественных размеров очки в черной роговой оправе. Второй - плечистый, рыжеватый, вихрастый молодой человек в заломленной</p>
<p>на затылок клетчатой кепке - был в ковбойке, жеваных белых брюках и в черных тапочках.</p>
<p>Первый был не кто иной, как <persName>Михаил Александрович Берлиоз</persName>, председатель правления одной из крупнейших московских литературных ассоциаций, сокращенно именуемой МАССОЛИТ, и редактор толстого художественного журнала, а молодой спутник его - поэт <persName>Иван Николаевич Понырев</persName>, пишущий под псевдонимом Бездомный.</p>
<p>Попав в тень чуть зеленеющих лип, писатели первым долгом бросились к пестро раскрашенной будочке с надписью «Пиво и воды».</p>
<p>Да, следует отметить первую странность этого страшного майского вечера. Не только у будочки, но и во всей аллее, параллельной Малой Бронной улице, не оказалось ни одного человека. В тот час, когда уж, кажется, и сил не было дышать, когда солнце, раскалив Москву, в сухом тумане валилось кудато за Садовое кольцо, - никто не пришел под липы, никто не сел на скамейку, пуста была аллея.</p>
<p>— Дайте нарзану, — попросил <persName>Берлиоз</persName>.</p>
<p>— нарзану нету, — ответила женщина в будочке и почемуто обиделась.</p>
<p>— Пиво есть? —- сиплым голосом осведомился Бездомный.</p>
<p>— Пиво привезут к вечеру, — ответила женщина.</p>
<p>— А что есть? — спросил <persName>Берлиоз</persName>.</p>
<p>— Абрикосовая, только теплая, — сказала женщина.</p>
<p>— Ну, давайте, давайте, давайте!..</p>
<p>Абрикосовая дала обильную желтую пену, и в воздухе запахло парикмахерской. Напившись, литераторы немедленно начали икать, расплатились и уселись на скамейке лицом к пруду и спиной к Бронной.</p>
<p>Тут приключилась вторая странность, касающаяся одного Берлиоза. Он внезапно перестал икать, сердце его стукнуло и на мгновенье куда-то провалилось, потом вернулось, но ступой иглой, засевшей в нем. Кроме того, Берлиоза охватил необоснованный, но столь сильный страх, что ему захотелось тотчас же бежать с Патриарших без оглядки. Берлиоз тоскливо оглянулся, не понимая, что его напугало. Он побледнел, вытер лоб платком, подумал: «Что это со мной? Этого никогда не было... сердце шалит... я переутомился. Пожалуй, пора бросить все к черту и в Кисловодск...»</p>
<p>И тут знойный воздух сгустился перед ним, и соткался из этого воздуха прозрачный гражданин престранного вида.</p>
<p>На маленькой головке жокейский картузик, клетчатый кургузый воздушный же пиджачок… [ражданин ростом в сажень, но в плечах узок, худ неимоверно, и физиономия, прошу заметить, глумливая.</p>
<p>Жизнь Берлиоза складывалась так, что к необыкновенным явлениям он не привык. Еще более побледнев, он вытаращил глаза и в смятении подумал: «Этого не может быть!..»</p>
<p>Но это, увы, было, и длинный, сквозь которого видно, гражданин, не касаясь земли, качался перед ним и влево и вправо.</p>
<p>Тут ужас до того овладел Берлиозом, что он закрыл глаза.</p>
<p>А когда он их открыл, увидел, что все кончилось, марево растворилось, клетчатый исчез, а заодно и тупая игла выскочила из сердца.</p>
<p>— Фу ты черт! — воскликнул редактор, — ты знаешь, Иван, у меня сейчас едва удар от жары не сделался! Даже что-то вроде галлюцинации было, — он попытался усмехнуться, но в глазах его еще прыгала тревога, и руки дрожали.</p>
<p>Однако постепенно он успокоился, обмахнулся платком и, произнеся довольно бодро: «Ну‑с, итак...» — повел речь, прерванную питьем абрикосовой.</p>
<p>Речь эта, как впоследствии узнали, шла об Иисусе Христе.</p>
<p>Дело в том, что редактор заказал поэту для очередной книжки журнала большую антирелигиозную поэму. Эту поэму Иван Николаевич сочинил, и в очень короткий срок, но, к сожалению, ею редактора нисколько не удовлетворил. Очертил Бездомный главное действующее лицо своей поэмы, то есть Иисуса, очень черными красками, и тем не менее всю поэму приходилось, по мнению редактора, писать заново. И вот теперь редактор читал поэту нечто вроде лекции об Иисусе, с тем чтобы подчеркнуть основную ошибку поэта. Трудно сказать, что именно подвело Ивана Николаевича — изобразительная ли сила его таланта или полное незнакомство с вопросом, по которому он собирался писать, - но Иисус в его изображении получился ну совершенно как живой, хотя и не привлекающий к себе персонаж. Берлиоз же хотел доказать поэту, что главное не в том, каков был Иисус, плох ли, хорош ли, а в том, что Иисуса‑то этого, как личности, вовсе не существовало на свете и что все рассказы о нем - простые выдумки, самый обычный миф.</p>
<p>Надо заметить, что редактор был человеком начитанным и очень умело указывал в своей речи на древних историков, например, на знаменитого Филона Александрийского, на блестяще образованного Иосифа Флавия, никогда ни словом не упоминавших о существовании Иисуса. Обнаруживая солидную эрудицию, Михаил Александрович сообщил поэту, между прочим, и о том, что то место в ту‑й книге, в главе 44‑й знаменитых Тацитовых «Анналов», где говорится о казни Иисуса, — есть не что иное, как позднейшая поддельная вставка.</p>
<p>Поэт, для которого все, сообщаемое редактором, являв о новой новостей, внимательно слушал Михаила Александровича, усТТ ставив на него свои бойкие зеленые глаза, и лишь изредка икал, шепотом ругая абрикосовую воду.</p>
<p>— Нет ни одной восточной религии, — говорил Берлиоз, — в которой, как правило непорочная дева не произвела бы на свет бога. И христиане, не выдумав ничего нового, точно так же создали своего Иисуса, которого на самом деле никогда не было в живых. Вот на это-то и нужно сделать главный упор…</p>
<p>Высокий тенор Берлиоза разносился в пустынной аллее, и по мере того, как Михаил Александрович забирался в дебри, в которые может забираться, не рискуя свернуть себе шею, лишь очень образованный человек, — поэт узнавал все больше и больше интересного и полезного и про египетского Озириса, благостного бога и сына Неба и Земли, и про финикийского бога Фаммуза, и про Мардука, и даже про менее известного грозного бога Вицлипуцли, которого весьма почитали некогда ацтеки в Мексике.</p>
<p>И вот как раз в то время, когда Михаил Александрович рассказывал поэту о том, как ацтеки лепили из теста фигурку Вицлипуцли, в аллее показался первый человек.</p>
<p>Впоследствии, когда, откровенно говоря, было уже поздно, разные учреждения представили свои сводки с описанием этого человека. Сличение их не может не вызвать изумления. Так, в первой из них сказано, что человек этот был маленького роста, зубы имел золотые и хромал на правую ногу. Во второй — что человек был росту громадного, коронки имел платиновые, хромал на левую ногу. Третья лаконически сообщает, что особых примет у человека не было.</p>
<p>Приходится признать, что ни одна из этих сводок никуда не годится. Раньше всего: ни на какую ногу описываемый не хромал, и росту был не маленького и не громадного, а просто высокого. Что касается зубов, то с левой стороны у него были платиновые коронки, а с правой — золотые. Он был в дорогом сером костюме, в заграничных, в цвет костюма, туфлях. Серый берет он лихо заломил на ухо, под мышкой нес трость с черным набалдашником в виде головы пуделя. По виду — лет сороТ2. ка с лишним. Рот какой-то кривой. Выбрит гладко. Брюнет. Правый глаз черный, левый почемуто зеленый. Брови черные, но одна выше другой. Словом — иностранец.</p>
<p>Пройдя мимо скамьи, на которой помещались редактор и поэт, иностранец покосился на них, остановился и вдруг уселся на соседней скамейке, в двух шагах от приятелей.</p>
<p>«Немец», — подумал Берлиоз.</p>
<p>«Англичанин, — подумал Бездомный, — ишь, и не жарко ему в перчатках».</p>
<p>А иностранец окинул взглядом высокие дома, квадратом окаймлявшие пруд, причем заметно стало, что видит это место он впервые и что оно его заинтересовало. Он остановил свой взор на верхних этажах, ослепительно отражающих в стеклах изломанное и навсегда уходящее от Михаила Александровича солнце, затем перевел его вниз, где стекла начали предвечерне темнеть, чему-то снисходительно усмехнулся, прищурился, руки положил на набалдашник, а подбородок на руки.</p>
<p>— Ты, Иван, — говорил Берлиоз, — очень хорошо и сатирически изобразил, например, рождение Иисуса, сына божия, но сольто в том, что еще до Иисуса родился еще ряд сынов божиих, как, скажем, фригийский Аттис, коротко же говоря, ни один из них не рождался и никого не было, в том числе и Иисуса, и необходимо, чтобы ты, вместо рождения и, скажем, прихода волхвов, описал нелепые слухи об этом рождении... А то выходит по твоему рассказу, что он действительно родился!..</p>
<p>Тут Бездомный сделал попытку прекратить замучившую его икоту, задержав дыхание, отчего икнул мучительнее и громче, и в этот же момент Берлиоз прервал свою речь, потому что иностранец вдруг поднялся и направился к писателям.</p>
<p>Те поглядели на него удивленно.</p>
<p>— Извините меня, пожалуйста, — заговорил подошедший с иностранным акцентом, но не коверкая слов, — что я, не будучи знаком, позволяю себе... но предмет вашей ученой беседы настолько интересен, что...</p>
<p>Тут он вежливо снял берет, и друзьям ничего не оставалось, как приподняться и раскланяться.</p>
<p>«Нет, скорее француз...» — подумал Берлиоз.</p>
<p>«Поляк?..» — подумал Бездомный.</p>
<p>Необходимо добавить, что на поэта иностранец с первых же слов произвел отвратительное впечатление, а Берлиозу скорее понравился, то есть не то чтобы понравился, а... как бы выразиться... заинтересовал, что ли.</p>
<p>— Разрешите мне присесть? — вежливо попросил иностранец, и приятели как-то невольно раздвинулись; иностранец ловко уселся между ними и тотчас вступил в разговор.</p>
<p>— Если я не ослышался, вы изволили говорить, что Иисуса не было на свете? — спросил иностранец, обращая к Берлиозу свой левый зеленый глаз.</p>
<p>— Нет, вы не ослышались, — учтиво ответил Берлиоз, — именно это я и говорил.</p>
<p>— Ах, как интересно! — воскликнул иностранец.</p>
<p>«А какого черта ему надо?» — подумал Бездомный и нахмурился.</p>
<p>— А вы соглашались с вашим собеседником? — осведомился неизвестный, повернувшись вправо к Бездомному.</p>
<p>— На все сто! — подтвердил тот, любя выражаться вычурно и фигурально.</p>
<p>— Изумительно! — воскликнул непрошеный собеседник и, почему-то воровски оглянувшись и приглушив свой низкий голос, сказал: — Простите мою навязчивость, но я так понял, что вы, помимо всего прочего, еще и не верите в бога? — он сделал испуганные глаза и прибавил: — Клянусь, я никому не скажу.</p>
<p>— Да, мы не верим в бога, — чуть улыбнувшись испугу интуриста, ответил Берлиоз. —- Но об этом можно говорить совершенно свободно.</p>
<p>Иностранец откинулся на спинку скамейки и спросил, даже привизгнув от любопытства: — Вы - атеисты?!</p>
<p>— Да, мы - атеисты, — улыбаясь, ответил Берлиоз, а Бездомный подумал, рассердившись: «Вот прицепился, заграничный гусь!»</p>
<p>— Ох, какая прелесть! — вскричал удивительный иностранец и завертел головой, глядя то на одного, то на другого литератора.</p>
<p>— В нашей стране атеизм никого не удивляет, — дипломатически вежливо сказал Берлиоз, — большинство нашего населения сознательно и давно перестало верить сказкам о боге.</p>
<p>Тут иностранец отколол такую штуку: встал и пожал изумленному редактору руку, произнеся при этом слова: — Позвольте вас поблагодарить от всей души!</p>
<p>— За что это вы его благодарите? - заморгав, осведомился Бездомный.</p>
<p>— За очень важное сведение, которое мне, как путешественнику, чрезвычайно интересно, — многозначительно подняв палец, пояснил заграничный чудак.</p>
<p>Важное сведение, по‑видимому, действительно произвело на путешественника сильное впечатление, потому что он испуганно обвел глазами дома, как бы опасаясь в каждом окне увидеть по атеисту.</p>
<p>«Нет, он не англичанин...» — подумал Берлиоз, а Бездомный подумал: «[де это он так наловчился говорить по‑русски, вот что интересно!» — и опять нахмурился.</p>
<p>— Но, позвольте вас спросить, — после тревожного раздумья спросил заграничный гость, - как же быть с доказательствами бытия божия, коих, как известно, существует ровно пять?</p>
<p>— Увы! — с сожалением ответил Берлиоз, -— ни одно из этих доказательств ничего не стоит, и человечество давно сдал их в архив. Ведь согласитесь, что в области разума никакого доказательства существования бога быть не может.</p>
<p>— Браво! — вскричал иностранец, — браво! Вы полностью повторили мысль беспокойного старика Иммануила по этому поводу. Но вот курьез: он начисто разрушил все пять доказательств, а затем, как бы в насмешку над самим собою, соорудил собственное шестое доказательство!</p>
<p>— Доказательство Канта, - тонко улыбнувшись, возразил образованный редактор, — также неубедительно. И недаром Шиллер говорил, что кантовские рассуждения по этому вопросу могут удовлетворить только рабов, а Штраус просто смеялась над этим доказательством.</p>
<p>Берлиоз говорил, а сам в это время думал: «Но, все-таки, кто же он такой? И почему так хорошо говорит по‑русски?»</p>
<p>— Взять бы этого Канта, да за такие доказательства года на три в Соловки! — совершенно неожиданно бухнул Иван Николаевич.</p>
<p>— Иван! - сконфузившись, шепнул Берлиоз.</p>
<p>Но предложение отправить Канта в Соловки не только не поразило иностранца, но даже привело в восторг.</p>
<p>— Именно, именно, — закричал он, и левый зеленый глаз его, обращенный к Берлиозу, засверкал, — ему там самое место! Ведь говорил я ему тогда за завтраком: «Вы, профессор, воля ваша, что‑то нескладное придумали! Оно, может, и умно, но больно непонятно. Над вами потешаться будут».</p>
<p>Берлиоз выпучил глаза. «За завтраком... Канту?.. Что это он плетет?» — подумал он.</p>
<p>— Но, - продолжал иноземец, не смущаясь изумлением Берлиоза и обращаясь к поэту, — отправить его в Соловки невозможно по той причине, что он уже с лишком сто лет пребывает в местах значительно более отдаленных, чем Соловки, и извлечь его оттуда никоим образом нельзя, уверяю вас!</p>
<p>— А жаль! — отозвался задира‑поэт.</p>
<p>— И мне жаль! — подтвердил неизвестный, сверкая глазом, и продолжал: — Но вот какой вопрос меня беспокоит: ежели бога нет, то, спрашивается, кто же управляет жизнью человеческой и всем вообще распорядком на земле?</p>
<p>— Сам человек и управляет, — поспешил сердито ответить Бездомный на этот, признаться, не очень ясный вопрос.</p>
<p>— Виноват, — мягко отозвался неизвестный, — для того, чтобы управлять, нужно, как‑никак, иметь точный план на некоторый, хоть сколько‑нибудь приличный срок. Позвольте же вас спросить, как же может управлять человек, если он не только лишен возможности составить какой‑нибудь план хотя бы на смехотворно короткий срок, ну, лет, скажем, в тысячу, но не может ручаться даже за свой собственный завтрашний день? И, в самом деле, — тут неизвестный повернулся к Берлиозу, — вообразите, что вы, например, начнете управлять, распоряжаться и другими и собою, вообще, так сказать, входить во вкус, и вдругу вас... кхе... кхе... саркома легкого...</p>
<p>—тут иностранец сладко усмехнулся, как будто мысль о саркоме легкого доставила ему удовольствие, — да, саркома, — жмурясь, как кот, повторил он звучное слово, — и вот ваше управление закончилось! Ничья судьба, кроме своей собственной, вас более не интересует. Родные вам начинают лгать, вы, чуя неладное, бросаетесь к ученым врачам, затем к шарлатанам, а бывает, и к гадалкам. Как первое и второе, так и третье — совершенно бессмысленно, вы сами понимаете. И все это кончается трагически: тот, кто еще недавно полагал, что он чем‑то управляет, оказывается вдруг лежащим неподвижно в деревянном ящике, и окружающие, понимая, что толку от лежащего нет более никакого, сжигают его в печи. А бывает и еще хуже: только что человек соберется съездить в Кисловодск, — тут иностранец прищурился на Берлиоза, — пустяковое, казалось бы, дело, но и этого совершить не может, потому что неизвестно почему вдруг возьмет — поскользнется и попадет под трамвай! Неужели вы скажете, что это он сам собою управил так? Не правильнее ли думать, что управился с ним кто-то совсем другой?</p>
<p>— и здесь незнакомец рассмеялся странным смешком.</p>
<p>Берлиоз с великим вниманием слушал неприятный рассказ про саркому и трамвай, и какие‑то тревожные мысли начали мучить его. «Он не иностранец! Он не иностранец! — думал он, — он престранный субъект... Но позвольте, кто же он такой?»</p>
<p>— Вы хотите курить, как я вижу? — неожиданно обратился к Бездомному неизвестный, — вы какие предпочитаете?</p>
<p>— А увас разные, что ли, есть? — мрачно спросил поэт, у которого папиросы кончились.</p>
<p>— Какие предпочитаете? — повторил неизвестный.</p>
<p>— Ну, «Нашу марку», — злобно ответил Бездомный.</p>
<p>Незнакомец немедленно вытащил из кармана портсигар</p>
<p>— «Наша марка».</p>
<p>И редактора и поэта не столько поразило то, что нашлась в портсигаре именно «Наша марка», сколько сам портсигар. Он был громадных размеров, червонного золота, и на крышке его при открывании сверкнул синим и белым огнем бриллиантовый треугольник.</p>
<p>Тут литераторы подумали разно. Берлиоз: «Нет, иностранец!», а Бездомный: «Вот черт его возьми! А?»</p>
<p>Поэт и владелец портсигара закурили, а некурящий Берлиоз отказался.</p>
<p>«Надо будет ему возразить так, — решил Берлиоз, — да, человек смертен, никто против этого и не спорит. А дело в том, что...»</p>
<p>Однако он не успел выговорить этих слов, как заговорил иностранец:</p>
<p>— Да, человек смертен, но это было бы еще полбеды. Плохо то, что он иногда внезапно смертен, вот в чем фокус! И вообще не может сказать, что он будет делать в сегодняшний вечер.</p>
<p>«Какая‑то нелепая постановка вопроса...» —- помыслил Берлиоз и возразил:</p>
<p>— Ну, здесь уж есть преувеличение. Сегодняшний вечер мне известен более или менее точно. Само собой разумеется, что, если на Бронной мне свалится на голову кирпич…</p>
<p>— Кирпич ни с того ни с сего, — внушительно перебил неизвестный, — никому и никогда на голову не свалится. В частности же, уверяю вас, вам он ни в коем случае не угрожает. Вы умрете другой смертью.</p>
<p>— Может быть, вы знаете, какой именно? — с совершенно естественной иронией осведомился Берлиоз, вовлекаясь в какой-то действительно нелепый разговор, — и скажете мне?</p>
<p>— Охотно, — отозвался незнакомец. Он смерил Берлиоза взглядом, как будто собирался сшить ему костюм, сквозь зубы пробормотал что‑то вроде: «Раз, два… Меркурий во втором доме… луна ушла… шесть — несчастье… вечер — семь…» — и громко и радостно объявил: — Вам отрежут голову!</p>
<p>Бездомный дико и злобно вытаращил глаза на развязного неизвестного, а Берлиоз спросил, криво усмехнувшись:</p>
<p>— А кто именно? Враги? Интервенты?</p>
<p>— Нет, — ответил собеседник, — русская женщина, комсомолка.</p>
<p>— м… - промычал раздраженный шуточкой неизвестного Берлиоз, - ну, это, извините, маловероятно.</p>
<p>— Прошу и меня извинить, — ответил иностранец, — но это так. Да, мне хотелось бы спросить вас, что вы будете делать сегодня вечером, если это не секрет?</p>
<p>— Секрета нет. Сейчас я зайду к себе на Садовую, а потом в десять часов вечера в МАССОЛИТе состоится заседание, я буду на нем председательствовать.</p>
<p>— Нет, этого быть никак не может, — твердо возразил иностранец.</p>
<p>— Это почему?</p>
<p>— Потому, — ответил иностранец и прищуренными глазами поглядел в небо, где, предчувствуя вечернюю прохладу, бесшумно чертили черные птицы, — что Аннушка уже купила подсолнечное масло, и не только купила, но даже разлила. Так что заседание не состоится.</p>
<p>Тут, как вполне понятно, под липами наступило молчание.</p>
<p>— Простите, — после паузы заговорил Берлиоз, поглядывая на мелющего чепуху иностранца, — при чем здесь подсолнечное масло... и какая Аннушка?</p>
<p>— Подсолнечное масло здесь вот при чем, — вдруг заговорил Бездомный, очевидно, решив объявить незванному собеседнику войну, — вам не приходилось, гражданин, бывать когданибудь в лечебнице для душевнобольных?</p>
<p>— Иван!.. - тихо воскликнул Михаил Александрович.</p>
<p>Но иностранец ничуть не обиделся и превесело рассмеялся.</p>
<p>— Бывал, бывал и не раз! — вскричал он, смеясь, но не сводя несмеющегося глаза с поэта, — где я только не бывал! Жаль только, что я не удосужился спросить у профессора, что такое шизофрения. Так что вы уж сами узнайте это у него, Иван Николаевич!</p>
<p>— Откуда вы знаете, как меня зовут?</p>
<p>— Помилуйте, Иван Николаевич, кто же вас не знает?</p>
<p>— здесь иностранец вытащил из кармана вчерашний номер «Литературной газеты», и Иван Николаевич увидел на первой же странице свое изображение, а под ним свои собственные стихи. Но вчера еще радовавшее доказательство славы и популярности на этот раз ничуть не обрадовало поэта.</p>
<p>— Я извиняюсь, — сказал он, и лицо его потемнело, — вы не можете подождать минутку? Я хочу товарищу пару слов сказать.</p>
<p>— О, судовольствием! — воскликнул неизвестный, — здесь так хорошо под липами, а я, кстати, никуда и не спещу.</p>
<p>— Вот что, Миша, — зашептал поэт, оттащив Берлиоза в сторону, — он никакой не интурист, а шпион. Это русский эмигрант, перебравшгийся к нам. Спрашивай у него документы, а то уйдет…</p>
<p>— Ты думаешь? — встревоженно шепнул Берлиоз, а сам подумал: «А ведь он прав!»</p>
<p>— Уж ты мне верь, — засипел ему в ухо поэт, — он дурачком прикидывается, чтобы выспросить кое‑что. Ты слышишь, как он по‑русски говорит, — поэт говорил и косился, следя, чтобы неизвестный не удрал, — идем, задержим его, а то уйдет…</p>
<p>И поэт за руку потянул Берлиоза к скамейке.</p>
<p>Незнакомец не сидел, а стоял возле нее, держа в руках какую‑то книжечку в темно‑сером переплете, плотный конверт хорошей бумаги и визитную карточку.</p>
<p>— Извините меня, что я в пылу нашего спора забыл представить себя вам. Вот моя карточка, паспорт и приглашение прийти в Москву для консультации, — веско проговорил неизвестный, проницательно глядя на обоих литераторов.</p>
<p>Те сконфузились. «Черт, все слышал,» — подумал Берлиоз и вежливым жестом показал, что в предъявлении документов нет надобности.</p>
<p>Пока иностранец совал их редактору, поэт успел разглядеть на карточке напечатанное иностранными буквами слово «профессор» и начальную букву фамилии — двойное «В».</p>
<p>— Очень приятно, — тем временем смущенно бормотал редактор, и иностранец спрятал документы в карман.</p>
<p>Отношения таким образом были восстановлены, и все трое снова сели на скамью.</p>
<p>— Вы в качестве консультанта приглашены к нам, профессор? — спросил Берлиоз.</p>
<p>— Да, консультантом.</p>
<p>— Вы — немец? — осведомился Бездомный.</p>
</text>
